import { ReactNode } from 'react';
import { PLANT, DOCUMENT_CONTROL, RETENTION, TODAY } from '../../data/config';
import { useAuth } from '../../lib/auth';

function verificationHash(seed: string): string {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0;
  return Math.abs(h).toString(16).toUpperCase().padStart(8, '0');
}

export function PrintHeader({
  title, formatNumber, scopeLine, pageLabel,
}: { title: string; formatNumber: string; scopeLine?: string; pageLabel: string }) {
  return (
    <div className="print-header">
      <div>
        <div className="flex items-center gap-1.5 mb-1">
          <svg width="16" height="16" viewBox="0 0 120 120">
            <path d="M76.9 23.75 A 40 40 0 1 1 43.1 23.75" fill="none" stroke="#1B1F35" strokeWidth="10" strokeLinecap="round" />
            <circle cx="76.9" cy="23.75" r="8.5" fill="#ED3123" />
          </svg>
          <span style={{ fontFamily: 'Fraunces, Georgia, serif', fontWeight: 600, fontSize: 13, color: '#1B1F35' }}>Jukuto</span>
        </div>
        <div className="print-h1">{title}</div>
        <div style={{ fontSize: 9.5, color: '#363C4E', marginTop: 2 }}>{PLANT.name} · {PLANT.location}</div>
        {scopeLine && <div style={{ fontSize: 9.5, color: '#363C4E' }}>{scopeLine}</div>}
      </div>
      <div className="doc-block">
        <div>Doc No: {formatNumber}</div>
        <div>Rev: {DOCUMENT_CONTROL.revision} · {DOCUMENT_CONTROL.revisionDate}</div>
        <div>Issue Date: {DOCUMENT_CONTROL.issueDate}</div>
        <div>{pageLabel}</div>
      </div>
    </div>
  );
}

export function PrintFooter({ recordId }: { recordId: string }) {
  const { user } = useAuth();
  const hash = verificationHash(recordId + TODAY);
  return (
    <div className="print-footer">
      <span>System-generated record — Jukuto Competence Platform</span>
      <span>Generated by: {user?.name ?? 'System'} ({user?.role ?? '—'}) · {TODAY} 00:00 IST</span>
      <span>Data as-of: {TODAY}</span>
      <span>Retention: {RETENTION.periodLabel}</span>
      <span>{DOCUMENT_CONTROL.confidentiality}</span>
      <span>Ref: JKT-{recordId}-{hash}</span>
    </div>
  );
}

export function PrintPage({
  children, landscape, className = '',
}: { children: ReactNode; landscape?: boolean; className?: string }) {
  return <div className={`print-page ${landscape ? 'landscape' : ''} ${className}`}>{children}</div>;
}

export function PrintSection({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="print-section">
      <div className="print-section-title">{title}</div>
      {children}
    </div>
  );
}

export function PrintField({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div className="print-field">
      <div className="k">{label}</div>
      <div className="v">{value ?? <span style={{ fontStyle: 'italic', color: '#8890A0' }}>Not recorded</span>}</div>
    </div>
  );
}

export function PrintLineChart({
  label, values, unit = '', targetLine, width = 460, height = 90,
}: { label: string; values: { x: string; y: number }[]; unit?: string; targetLine?: number; width?: number; height?: number }) {
  if (values.length === 0) {
    return (
      <div style={{ fontSize: 10, fontStyle: 'italic', color: '#8890A0' }}>{label}: Not recorded</div>
    );
  }
  const padL = 28, padR = 8, padT = 10, padB = 18;
  const plotW = width - padL - padR;
  const plotH = height - padT - padB;
  const ys = values.map(v => v.y);
  const maxY = Math.max(...ys, targetLine ?? 0) * 1.1 || 1;
  const minY = Math.min(0, Math.min(...ys));
  const xFor = (i: number) => padL + (values.length === 1 ? plotW / 2 : (i / (values.length - 1)) * plotW);
  const yFor = (v: number) => padT + plotH - ((v - minY) / (maxY - minY || 1)) * plotH;
  const points = values.map((v, i) => `${xFor(i)},${yFor(v.y)}`).join(' ');

  return (
    <div style={{ marginBottom: 4 }}>
      <div style={{ fontSize: 9, fontWeight: 600, color: '#1B1F35', marginBottom: 2 }}>{label}</div>
      <svg width={width} height={height} style={{ overflow: 'visible' }}>
        <line x1={padL} y1={padT} x2={padL} y2={padT + plotH} stroke="#C9CFDD" strokeWidth={1} />
        <line x1={padL} y1={padT + plotH} x2={padL + plotW} y2={padT + plotH} stroke="#C9CFDD" strokeWidth={1} />
        <text x={2} y={padT + 4} fontSize={7} fill="#363C4E">{Math.round(maxY)}{unit}</text>
        <text x={2} y={padT + plotH} fontSize={7} fill="#363C4E">{Math.round(minY)}{unit}</text>
        {targetLine !== undefined && (
          <line x1={padL} y1={yFor(targetLine)} x2={padL + plotW} y2={yFor(targetLine)} stroke="#ED3123" strokeWidth={1} strokeDasharray="3,2" />
        )}
        <polyline points={points} fill="none" stroke="#1B1F35" strokeWidth={1.6} />
        {values.map((v, i) => (
          <circle key={i} cx={xFor(i)} cy={yFor(v.y)} r={2.2} fill="#1B1F35" />
        ))}
        {values.map((v, i) => (
          <text key={i} x={xFor(i)} y={padT + plotH + 12} fontSize={6.5} fill="#363C4E" textAnchor="middle">{v.x}</text>
        ))}
      </svg>
    </div>
  );
}

export function SignatureBlock({
  recommended, verified, authorised, acknowledged, auditTrailRef,
}: {
  recommended?: { name: string; id: string; role: string; timestamp: string } | null;
  verified?: { name: string; id: string; role: string } | null;
  authorised?: { name: string; id: string; role: string; timestamp: string } | null;
  acknowledged?: { name: string; id: string } | null;
  auditTrailRef: string;
}) {
  const cells: { head: string; e?: { name: string; id: string; role?: string; timestamp?: string } | null }[] = [
    { head: 'Recommended by (Trainer)', e: recommended },
    { head: 'Verified by (Training Coordinator)', e: verified },
    { head: 'Authorised by (Quality Head)', e: authorised },
    { head: 'Acknowledged by (Operator)', e: acknowledged },
  ];
  return (
    <div className="sig-grid">
      {cells.map((c, i) => (
        <div className="sig-cell" key={i}>
          <div className="head">{c.head}</div>
          <div className="sig-label">Name</div>
          <div className="sig-value">{c.e?.name ?? '—'}</div>
          <div className="sig-label" style={{ marginTop: 4 }}>Emp ID</div>
          <div className="sig-value">{c.e?.id ?? '—'}</div>
          {c.e?.timestamp ? (
            <>
              <div style={{ fontSize: 8, marginTop: 6, color: '#2B4BFF', fontWeight: 700 }}>
                ELECTRONICALLY SIGNED — see audit trail ref {auditTrailRef}
              </div>
              <div className="sig-label" style={{ marginTop: 3 }}>Timestamp</div>
              <div className="sig-value" style={{ fontSize: 8.5 }}>{c.e.timestamp}</div>
            </>
          ) : (
            <>
              <div className="sig-line" />
              <div className="sig-label">Signature (wet ink)</div>
              <div className="sig-line" style={{ marginTop: 8 }} />
              <div className="sig-label">Date</div>
            </>
          )}
        </div>
      ))}
    </div>
  );
}
